[[pages]]
path = "app.py"
name = "Home"
icon = "ğŸ "

[[pages]]
path = "pages/dashboard.py"
name = "Dashboard"
icon = "ğŸ“Š"

[[pages]]
path = "pages/forecasting.py"
name = "Forecasting"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/page_conversation.py"
name = "Conversation"
icon = "ğŸ’¬"
